### ISSUE TITLE
databunch API seems to be broken.

### ISSUE THREAD

**Issue by at110** [renato145/fastai_scans#3]
Hi Renato,

I updated my fastai repository and looking like it broke fastai_scans.
for 
```
data = (fastai_scans.SegmentationItemList.from_paths(train_data_bolz, train_labels_bolz)
                                         .random_split_by_pct(0.2, seed=7)
                                         .label_from_bcolz()
                                         .transform(fastai_scans.get_transforms(), tfm_y=True)
                                         .databunch(bs=bs)
                                         .normalize())
```
I am getting 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-12458b377da7> in <module>
      3                                          .label_from_bcolz()
      4                                          .transform(fastai_scans.get_transforms(), tfm_y=True)
----> 5                                          .databunch(bs=bs)
      6                                          .normalize())

~/fastai-fork/fastai/data_block.py in databunch(self, path, bs, val_bs, num_workers, dl_tfms, device, collate_fn, no_check, **kwargs)
    494         path = Path(ifnone(path, self.path))
    495         data = self.x._bunch.create(self.train, self.valid, test_ds=self.test, path=path, bs=bs, val_bs=val_bs, 
--> 496                                     num_workers=num_workers, device=device, collate_fn=collate_fn, no_check=no_check, **kwargs)
    497         if getattr(self, 'normalize', False):#In case a normalization was serialized
    498             norm = self.normalize

~/tutorials/fastai_scans/fastai_scans/data.py in create(cls, train_ds, valid_ds, **kwargs)
     25     @classmethod
     26     def create(cls, train_ds, valid_ds, **kwargs):
---> 27         return super().create(train_ds, valid_ds,  **kwargs)
     28 
     29     def normalize(self, format3d=True, do_x=True, do_y=False):

TypeError: create() got multiple values for keyword argument 'num_workers'

**Comment by at110** [comment]
it was simple change...
```
class BcolzDataBunch(DataBunch):
    @classmethod
    def create(cls, train_ds, valid_ds, **kwargs):
        return super().create(train_ds, valid_ds,  num_workers=0, **kwargs)
```
to
```
class BcolzDataBunch(DataBunch):
    @classmethod
    def create(cls, train_ds, valid_ds, **kwargs):
        return super().create(train_ds, valid_ds,  **kwargs)
```

Solved issue

**Comment by renato145** [comment]
It should be working now :)

**Comment by at110** [comment]
Thanks @renato145
